### ISSUE TITLE
Users want a single website to submit their information to find ridesharers.

### ISSUE THREAD

**Issue by jc-tung** [nareha/UCLAX#6]
# User Story
As a user, I want a single centralized website where I can submit my information to find ridesharers.

# Detailed Description
This story primarily is concerned with the initial setup of the website and the features that will allow users to find ridesharers.

# Acceptance Criteria
- [x] #10
- [x] #16
- [x] #15
- [x] #12
- [x] #11
- [x] #40

**Comment by nareha** [comment]
Completed in Sprint 1.
